In [1]:
from google.colab import auth
auth.authenticate_user()

In [2]:
project_id = "major-project-407515"
!gcloud config set project {project_id}

Updated property [core/project].

In [3]:
import pandas as pd
df = pd.read_csv("gs://project_major/Major_Project/DATA.csv")

In [4]:
df = df.iloc[:, 1:]

In [5]:
df

,incident_datetime,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,report_type_code,...,latitude,longitude,point,:@computed_region_26cr_cadq,:@computed_region_qgnn_b9vv,:@computed_region_jwn9_ihcz,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_n4xg_c4py,:@computed_region_jg9y_a9du
0,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2021-01-23T12:45:00.000,99878909027,998789,210051968,II,...,37.729910,-122.397177,"{'type': 'Point', 'coordinates': [-122.3971768...",9.0,2.0,86.0,NaN,NaN,NaN,NaN
1,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-08-04T10:39:00.000,117813874000,1178138,220517916,II,...,37.783933,-122.412595,"{'type': 'Point', 'coordinates': [-122.4125952...",10.0,5.0,20.0,1.0,NaN,1.0,NaN
2,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-07-29T13:00:00.000,117626571000,1176265,220503460,II,...,37.779695,-122.442605,"{'type': 'Point', 'coordinates': [-122.4426053...",6.0,7.0,13.0,NaN,NaN,NaN,NaN
3,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-10-10T15:52:00.000,120201009320,1202010,220696742,II,...,37.773455,-122.427357,"{'type': 'Point', 'coordinates': [-122.4273574...",11.0,4.0,26.0,NaN,NaN,NaN,NaN
4,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2023-02-13T12:41:00.000,124404409340,1244044,230106985,II,...,37.734748,-122.399375,"{'type': 'Point', 'coordinates': [-122.3993746...",9.0,2.0,87.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801979,2023-12-06T20:51:00.000,2023-12-06T00:00:00.000,20:51,2023,Wednesday,2023-12-06T20:51:00.000,134512227175,1345122,230858120,II,...,37.783724,-122.414242,"{'type': 'Point', 'coordinates': [-122.4142415...",10.0,5.0,20.0,1.0,NaN,1.0,NaN
801980,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512328160,1345123,230858136,II,...,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN
801981,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512307100,1345123,230858136,II,...,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN
801982,2023-12-06T21:55:00.000,2023-12-06T00:00:00.000,21:55,2023,Wednesday,2023-12-06T21:59:00.000,134512551050,1345125,230858211,II,...,37.784657,-122.414430,"{'type': 'Point', 'coordinates': [-122.4144301...",10.0,5.0,20.0,1.0,NaN,NaN,NaN
801983,2023-12-06T23:13:00.000,2023-12-06T00:00:00.000,23:13,2023,Wednesday,2023-12-06T23:15:00.000,134513372000,1345133,230858283,II,...,37.744681,-122.481181,"{'type': 'Point', 'coordinates': [-122.4811812...",7.0,10.0,40.0,NaN,NaN,NaN,NaN

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
df['ID'] = df.index

In [8]:
df

,incident_datetime,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id,incident_number,report_type_code,report_type_description,incident_code,incident_category,incident_subcategory,incident_description,resolution,police_district,filed_online,cad_number,intersection,cnn,analysis_neighborhood,supervisor_district,supervisor_district_2012,latitude,longitude,point,:@computed_region_26cr_cadq,:@computed_region_qgnn_b9vv,:@computed_region_jwn9_ihcz,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_n4xg_c4py,:@computed_region_jg9y_a9du,ID
0,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2021-01-23T12:45:00.000,99878909027,998789,210051968,II,Initial,9027,Fraud,Fraud,False Personation,Open or Active,Out of SF,NaN,210231480.0,WILLIAMS AVE \ NEPTUNE ST,20537000.0,Bayview Hunters Point,10.0,10.0,37.729910,-122.397177,"{'type': 'Point', 'coordinates': [-122.3971768...",9.0,2.0,86.0,NaN,NaN,NaN,NaN,0
1,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-08-04T10:39:00.000,117813874000,1178138,220517916,II,Initial,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,Tenderloin,NaN,222161054.0,EDDY ST \ JONES ST,24929000.0,Tenderloin,5.0,6.0,37.783933,-122.412595,"{'type': 'Point', 'coordinates': [-122.4125952...",10.0,5.0,20.0,1.0,NaN,1.0,NaN,1
2,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-07-29T13:00:00.000,117626571000,1176265,220503460,II,Initial,71000,Lost Property,Lost Property,Lost Property,Open or Active,Park,NaN,222101511.0,FORTUNA AVE \ ANZAVISTA AVE,26369000.0,Lone Mountain/USF,2.0,2.0,37.779695,-122.442605,"{'type': 'Point', 'coordinates': [-122.4426053...",6.0,7.0,13.0,NaN,NaN,NaN,NaN,2
3,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-10-10T15:52:00.000,120201009320,1202010,220696742,II,Initial,9320,Fraud,Fraud,"Access Card, incl. Credit, Phone, ATM, Fraudul...",Open or Active,Northern,NaN,222832233.0,PAGE ST \ BUCHANAN ST,25903000.0,Hayes Valley,5.0,5.0,37.773455,-122.427357,"{'type': 'Point', 'coordinates': [-122.4273574...",11.0,4.0,26.0,NaN,NaN,NaN,NaN,3
4,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2023-02-13T12:41:00.000,124404409340,1244044,230106985,II,Initial,9340,Fraud,Fraud,"Credit Application, Fraudulent",Open or Active,Bayview,NaN,230441396.0,THOMAS AVE \ QUINT ST,20735000.0,Bayview Hunters Point,10.0,10.0,37.734748,-122.399375,"{'type': 'Point', 'coordinates': [-122.3993746...",9.0,2.0,87.0,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801979,2023-12-06T20:51:00.000,2023-12-06T00:00:00.000,20:51,2023,Wednesday,2023-12-06T20:51:00.000,134512227175,1345122,230858120,II,Initial,27175,Other Miscellaneous,Other,Evading a Police Officer Recklessly,Open or Active,Tenderloin,NaN,233402862.0,EDDY ST \ LEAVENWORTH ST,24935000.0,Tenderloin,5.0,6.0,37.783724,-122.414242,"{'type': 'Point', 'coordinates': [-122.4142415...",10.0,5.0,20.0,1.0,NaN,1.0,NaN,801979
801980,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512328160,1345123,230858136,II,Initial,28160,Malicious Mischief,Vandalism,"Malicious Mischief, Vandalism to Vehicle",Open or Active,Northern,NaN,233402895.0,FILLMORE ST \ BUSH ST,26608000.0,Pacific Heights,5.0,5.0,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN,801980
801981,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512307100,1345123,230858136,II,Initial,7100,Vandalism,Vandalism,"Vehicle, Tampering",Open or Active,Northern,NaN,233402895.0,FILLMORE ST \ BUSH ST,26608000.0,Pacific Heights,5.0,5.0,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN,801981
801982,2023-12-06T21:55:00.000,2023-12-06T00:00:00.000,21:55,2023,Wednesday,2023-12-06T21:59:00.000,134512551050,1345125,230858211,II,Initial,51050,Non-Criminal,Non-Criminal,"Aided case, Naloxone Deployment",Open or Active,Tenderloin,NaN,233403010.0,ELLIS ST \ LEAVENWORTH ST,25139000.0,Tenderloin,5.0,6.0,37.784657,-122.414430,"{'type': 'Point', 'coordinates': [-122.4144301...",10.0,5.0,20.0,1.0,NaN,NaN,NaN,801982
801983,2023-12-06T23:13:00.000,2023-12-06T00:00:00.000,23:13,2023,Wednesday,2023-12-06T23:15:00.000,134513372000,1345133,230858283,II,Initial,72000,Non-Criminal,Non-Criminal,Found Property,Open or Active,Taraval,NaN,233403166.0,SANTIAGO ST \ 24TH AVE,23262000.0,Sunset/Parkside,4.0,4.0,37.744681,-122.481181,"{'type': 'Point', 'coordinates': [-122.4811812...",7.0,10.0,40.0,NaN,NaN,NaN,NaN,801983

In [9]:
df.columns

Index(['incident_datetime', 'incident_date', 'incident_time', 'incident_year',
       'incident_day_of_week', 'report_datetime', 'row_id', 'incident_id',
       'incident_number', 'report_type_code', 'report_type_description',
       'incident_code', 'incident_category', 'incident_subcategory',
       'incident_description', 'resolution', 'police_district', 'filed_online',
       'cad_number', 'intersection', 'cnn', 'analysis_neighborhood',
       'supervisor_district', 'supervisor_district_2012', 'latitude',
       'longitude', 'point', ':@computed_region_26cr_cadq',
       ':@computed_region_qgnn_b9vv', ':@computed_region_jwn9_ihcz',
       ':@computed_region_h4ep_8xdi', ':@computed_region_nqbw_i6c3',
       ':@computed_region_n4xg_c4py', ':@computed_region_jg9y_a9du', 'ID'],
      dtype='object')

In [10]:
datetime_dim = df[['incident_datetime']].reset_index(drop = True)

In [11]:
datetime_dim

              incident_datetime
0       2018-01-01T00:00:00.000
1       2018-01-01T00:00:00.000
2       2018-01-01T00:00:00.000
3       2018-01-01T00:00:00.000
4       2018-01-01T00:00:00.000
...                         ...
801979  2023-12-06T20:51:00.000
801980  2023-12-06T21:02:00.000
801981  2023-12-06T21:02:00.000
801982  2023-12-06T21:55:00.000
801983  2023-12-06T23:13:00.000

[801984 rows x 1 columns]

In [12]:
datetime_dim['incident_datetime'] = pd.to_datetime(df['incident_datetime'])

In [13]:
datetime_dim['day'] = datetime_dim['incident_datetime'].dt.day
datetime_dim['month'] = datetime_dim['incident_datetime'].dt.month
datetime_dim['year'] = datetime_dim['incident_datetime'].dt.year
datetime_dim['quarter'] = datetime_dim['incident_datetime'].dt.quarter
datetime_dim['weekday'] = datetime_dim['day'].apply(lambda x: 'y' if x < 5 else 'n')
datetime_dim['weekend'] = datetime_dim['day'].apply(lambda x: 'n' if x < 5 else 'y')


datetime_dim['datetime_id'] = datetime_dim.index

In [14]:
datetime_dim

,incident_datetime,day,month,year,quarter,weekday,weekend,datetime_id
0,2018-01-01 00:00:00,1,1,2018,1,y,n,0
1,2018-01-01 00:00:00,1,1,2018,1,y,n,1
2,2018-01-01 00:00:00,1,1,2018,1,y,n,2
3,2018-01-01 00:00:00,1,1,2018,1,y,n,3
4,2018-01-01 00:00:00,1,1,2018,1,y,n,4
...,...,...,...,...,...,...,...,...
801979,2023-12-06 20:51:00,6,12,2023,4,n,y,801979
801980,2023-12-06 21:02:00,6,12,2023,4,n,y,801980
801981,2023-12-06 21:02:00,6,12,2023,4,n,y,801981
801982,2023-12-06 21:55:00,6,12,2023,4,n,y,801982
801983,2023-12-06 23:13:00,6,12,2023,4,n,y,801983

In [15]:
datetime_dim.columns

Index(['incident_datetime', 'day', 'month', 'year', 'quarter', 'weekday',
       'weekend', 'datetime_id'],
      dtype='object')

In [16]:
time_dim = df[['incident_datetime']].reset_index(drop = True)
time_dim['incident_datetime'] = pd.to_datetime(df['incident_datetime'])
time_dim['time'] = time_dim['incident_datetime'].dt.strftime('%H:%M:%S')
time_dim['hour'] = time_dim['incident_datetime'].dt.hour
time_dim['minute'] = time_dim['incident_datetime'].dt.minute
time_dim['second'] = time_dim['incident_datetime'].dt.second
time_dim['time_id'] = time_dim.index

In [17]:
time_dim

         incident_datetime      time  hour  minute  second  time_id
0      2018-01-01 00:00:00  00:00:00     0       0       0        0
1      2018-01-01 00:00:00  00:00:00     0       0       0        1
2      2018-01-01 00:00:00  00:00:00     0       0       0        2
3      2018-01-01 00:00:00  00:00:00     0       0       0        3
4      2018-01-01 00:00:00  00:00:00     0       0       0        4
...                    ...       ...   ...     ...     ...      ...
801979 2023-12-06 20:51:00  20:51:00    20      51       0   801979
801980 2023-12-06 21:02:00  21:02:00    21       2       0   801980
801981 2023-12-06 21:02:00  21:02:00    21       2       0   801981
801982 2023-12-06 21:55:00  21:55:00    21      55       0   801982
801983 2023-12-06 23:13:00  23:13:00    23      13       0   801983

[801984 rows x 6 columns]

In [18]:
time_dim.columns

Index(['incident_datetime', 'time', 'hour', 'minute', 'second', 'time_id'], dtype='object')

In [19]:
location_dim = df[['latitude', 'longitude']].reset_index(drop=True)
location_dim['location_id'] = location_dim.index

In [20]:
location_dim

         latitude   longitude  location_id
0       37.729910 -122.397177            0
1       37.783933 -122.412595            1
2       37.779695 -122.442605            2
3       37.773455 -122.427357            3
4       37.734748 -122.399375            4
...           ...         ...          ...
801979  37.783724 -122.414242       801979
801980  37.787021 -122.433460       801980
801981  37.787021 -122.433460       801981
801982  37.784657 -122.414430       801982
801983  37.744681 -122.481181       801983

[801984 rows x 3 columns]

In [21]:
location_dim.columns

Index(['latitude', 'longitude', 'location_id'], dtype='object')

In [22]:
incident_dim = df[['incident_id', 'incident_code', 'incident_category', 'incident_subcategory', 'incident_description']].reset_index(drop=True)
incident_dim['Inci_id'] = incident_dim.index

In [23]:
incident_dim

,incident_id,incident_code,incident_category,incident_subcategory,incident_description,Inci_id
0,998789,9027,Fraud,Fraud,False Personation,0
1,1178138,74000,Missing Person,Missing Adult,Missing Adult,1
2,1176265,71000,Lost Property,Lost Property,Lost Property,2
3,1202010,9320,Fraud,Fraud,"Access Card, incl. Credit, Phone, ATM, Fraudul...",3
4,1244044,9340,Fraud,Fraud,"Credit Application, Fraudulent",4
...,...,...,...,...,...,...
801979,1345122,27175,Other Miscellaneous,Other,Evading a Police Officer Recklessly,801979
801980,1345123,28160,Malicious Mischief,Vandalism,"Malicious Mischief, Vandalism to Vehicle",801980
801981,1345123,7100,Vandalism,Vandalism,"Vehicle, Tampering",801981
801982,1345125,51050,Non-Criminal,Non-Criminal,"Aided case, Naloxone Deployment",801982
801983,1345133,72000,Non-Criminal,Non-Criminal,Found Property,801983

In [24]:
incident_dim.columns

Index(['incident_id', 'incident_code', 'incident_category',
       'incident_subcategory', 'incident_description', 'Inci_id'],
      dtype='object')

In [25]:
resolution_dim = df[['resolution']].reset_index(drop=True)
resolution_dim['resolution_id'] = location_dim.index

In [26]:
resolution_dim

            resolution  resolution_id
0       Open or Active              0
1       Open or Active              1
2       Open or Active              2
3       Open or Active              3
4       Open or Active              4
...                ...            ...
801979  Open or Active         801979
801980  Open or Active         801980
801981  Open or Active         801981
801982  Open or Active         801982
801983  Open or Active         801983

[801984 rows x 2 columns]

In [27]:
resolution_dim.columns

Index(['resolution', 'resolution_id'], dtype='object')

In [28]:
fact_table = df.merge(datetime_dim, left_on='ID', right_on='datetime_id') \
             .merge(time_dim, left_on='ID', right_on='time_id') \
             .merge(location_dim, left_on='ID', right_on='location_id') \
             .merge(incident_dim, left_on='ID', right_on='Inci_id') \
             .merge(resolution_dim, left_on='ID', right_on='resolution_id')\

In [29]:
fact_table

,incident_datetime_x,incident_date,incident_time,incident_year,incident_day_of_week,report_datetime,row_id,incident_id_x,incident_number,report_type_code,report_type_description,incident_code_x,incident_category_x,incident_subcategory_x,incident_description_x,resolution_x,police_district,filed_online,cad_number,intersection,cnn,analysis_neighborhood,supervisor_district,supervisor_district_2012,latitude_x,longitude_x,point,:@computed_region_26cr_cadq,:@computed_region_qgnn_b9vv,:@computed_region_jwn9_ihcz,:@computed_region_h4ep_8xdi,:@computed_region_nqbw_i6c3,:@computed_region_n4xg_c4py,:@computed_region_jg9y_a9du,ID,incident_datetime_y,day,month,year,quarter,weekday,weekend,datetime_id,incident_datetime,time,hour,minute,second,time_id,latitude_y,longitude_y,location_id,incident_id_y,incident_code_y,incident_category_y,incident_subcategory_y,incident_description_y,Inci_id,resolution_y,resolution_id
0,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2021-01-23T12:45:00.000,99878909027,998789,210051968,II,Initial,9027,Fraud,Fraud,False Personation,Open or Active,Out of SF,NaN,210231480.0,WILLIAMS AVE \ NEPTUNE ST,20537000.0,Bayview Hunters Point,10.0,10.0,37.729910,-122.397177,"{'type': 'Point', 'coordinates': [-122.3971768...",9.0,2.0,86.0,NaN,NaN,NaN,NaN,0,2018-01-01 00:00:00,1,1,2018,1,y,n,0,2018-01-01 00:00:00,00:00:00,0,0,0,0,37.729910,-122.397177,0,998789,9027,Fraud,Fraud,False Personation,0,Open or Active,0
1,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-08-04T10:39:00.000,117813874000,1178138,220517916,II,Initial,74000,Missing Person,Missing Adult,Missing Adult,Open or Active,Tenderloin,NaN,222161054.0,EDDY ST \ JONES ST,24929000.0,Tenderloin,5.0,6.0,37.783933,-122.412595,"{'type': 'Point', 'coordinates': [-122.4125952...",10.0,5.0,20.0,1.0,NaN,1.0,NaN,1,2018-01-01 00:00:00,1,1,2018,1,y,n,1,2018-01-01 00:00:00,00:00:00,0,0,0,1,37.783933,-122.412595,1,1178138,74000,Missing Person,Missing Adult,Missing Adult,1,Open or Active,1
2,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-07-29T13:00:00.000,117626571000,1176265,220503460,II,Initial,71000,Lost Property,Lost Property,Lost Property,Open or Active,Park,NaN,222101511.0,FORTUNA AVE \ ANZAVISTA AVE,26369000.0,Lone Mountain/USF,2.0,2.0,37.779695,-122.442605,"{'type': 'Point', 'coordinates': [-122.4426053...",6.0,7.0,13.0,NaN,NaN,NaN,NaN,2,2018-01-01 00:00:00,1,1,2018,1,y,n,2,2018-01-01 00:00:00,00:00:00,0,0,0,2,37.779695,-122.442605,2,1176265,71000,Lost Property,Lost Property,Lost Property,2,Open or Active,2
3,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2022-10-10T15:52:00.000,120201009320,1202010,220696742,II,Initial,9320,Fraud,Fraud,"Access Card, incl. Credit, Phone, ATM, Fraudul...",Open or Active,Northern,NaN,222832233.0,PAGE ST \ BUCHANAN ST,25903000.0,Hayes Valley,5.0,5.0,37.773455,-122.427357,"{'type': 'Point', 'coordinates': [-122.4273574...",11.0,4.0,26.0,NaN,NaN,NaN,NaN,3,2018-01-01 00:00:00,1,1,2018,1,y,n,3,2018-01-01 00:00:00,00:00:00,0,0,0,3,37.773455,-122.427357,3,1202010,9320,Fraud,Fraud,"Access Card, incl. Credit, Phone, ATM, Fraudul...",3,Open or Active,3
4,2018-01-01T00:00:00.000,2018-01-01T00:00:00.000,00:00,2018,Monday,2023-02-13T12:41:00.000,124404409340,1244044,230106985,II,Initial,9340,Fraud,Fraud,"Credit Application, Fraudulent",Open or Active,Bayview,NaN,230441396.0,THOMAS AVE \ QUINT ST,20735000.0,Bayview Hunters Point,10.0,10.0,37.734748,-122.399375,"{'type': 'Point', 'coordinates': [-122.3993746...",9.0,2.0,87.0,NaN,NaN,NaN,NaN,4,2018-01-01 00:00:00,1,1,2018,1,y,n,4,2018-01-01 00:00:00,00:00:00,0,0,0,4,37.734748,-122.399375,4,1244044,9340,Fraud,Fraud,"Credit Application, Fraudulent",4,Open or Active,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801979,2023-12-06T20:51:00.000,2023-12-06T00:00:00.000,20:51,2023,Wednesday,2023-12-06T20:51:00.000,134512227175,1345122,230858120,II,Initial,27175,Other Miscellaneous,Other,Evading a Police Officer Recklessly,Open or Active,Tenderloin,NaN,233402862.0,EDDY ST \ LEAVENWORTH ST,24935000.0,Tenderloin,5.0,6.0,37.783724,-122.414242,"{'type': 'Point', 'coordinates': [-122.4142415...",10.0,5.0,20.0,1.0,NaN,1.0,NaN,801979,2023-12-06 20:51:00,6,12,2023,4,n,y,801979,2023-12-06 20:51:00,20:51:00,20,51,0,801979,37.783724,-122.414242,801979,1345122,27175,Other Miscellaneous,Other,Evading a Police Officer Recklessly,801979,Open or Active,801979
801980,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512328160,1345123,230858136,II,Initial,28160,Malicious Mischief,Vandalism,"Malicious Mischief, Vandalism to Vehicle",Open or Active,Northern,NaN,233402895.0,FILLMORE ST \ BUSH ST,26608000.0,Pacific Heights,5.0,5.0,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN,801980,2023-12-06 21:02:00,6,12,2023,4,n,y,801980,2023-12-06 21:02:00,21:02:00,21,2,0,801980,37.787021,-122.433460,801980,1345123,28160,Malicious Mischief,Vandalism,"Malicious Mischief, Vandalism to Vehicle",801980,Open or Active,801980
801981,2023-12-06T21:02:00.000,2023-12-06T00:00:00.000,21:02,2023,Wednesday,2023-12-06T21:06:00.000,134512307100,1345123,230858136,II,Initial,7100,Vandalism,Vandalism,"Vehicle, Tampering",Open or Active,Northern,NaN,233402895.0,FILLMORE ST \ BUSH ST,26608000.0,Pacific Heights,5.0,5.0,37.787021,-122.433460,"{'type': 'Point', 'coordinates': [-122.4334599...",11.0,4.0,103.0,NaN,NaN,NaN,NaN,801981,2023-12-06 21:02:00,6,12,2023,4,n,y,801981,2023-12-06 21:02:00,21:02:00,21,2,0,801981,37.787021,-122.433460,801981,1345123,7100,Vandalism,Vandalism,"Vehicle, Tampering",801981,Open or Active,801981
801982,2023-12-06T21:55:00.000,2023-12-06T00:00:00.000,21:55,2023,Wednesday,2023-12-06T21:59:00.000,134512551050,1345125,230858211,II,Initial,51050,Non-Criminal,Non-Criminal,"Aided case, Naloxone Deployment",Open or Active,Tenderloin,NaN,233403010.0,ELLIS ST \ LEAVENWORTH ST,25139000.0,Tenderloin,5.0,6.0,37.784657,-122.414430,"{'type': 'Point', 'coordinates': [-122.4144301...",10.0,5.0,20.0,1.0,NaN,NaN,NaN,801982,2023-12-06 21:55:00,6,12,2023,4,n,y,801982,2023-12-06 21:55:00,21:55:00,21,55,0,801982,37.784657,-122.414430,801982,1345125,51050,Non-Criminal,Non-Criminal,"Aided case, Naloxone Deployment",801982,Open or Active,801982
801983,2023-12-06T23:13:00.000,2023-12-06T00:00:00.000,23:13,2023,Wednesday,2023-12-06T23:15:00.000,134513372000,1345133,230858283,II,Initial,72000,Non-Criminal,Non-Criminal,Found Property,Open or Active,Taraval,NaN,233403166.0,SANTIAGO ST \ 24TH AVE,23262000.0,Sunset/Parkside,4.0,4.0,37.744681,-122.481181,"{'type': 'Point', 'coordinates': [-122.4811812...",7.0,10.0,40.0,NaN,NaN,NaN,NaN,801983,2023-12-06 23:13:00,6,12,2023,4,n,y,801983,2023-12-06 23:13:00,23:13:00,23,13,0,801983,37.744681,-122.481181,801983,1345133,72000,Non-Criminal,Non-Criminal,Found Property,801983,Open or Active,801983

In [30]:
fact_table.columns

Index(['incident_datetime_x', 'incident_date', 'incident_time',
       'incident_year', 'incident_day_of_week', 'report_datetime', 'row_id',
       'incident_id_x', 'incident_number', 'report_type_code',
       'report_type_description', 'incident_code_x', 'incident_category_x',
       'incident_subcategory_x', 'incident_description_x', 'resolution_x',
       'police_district', 'filed_online', 'cad_number', 'intersection', 'cnn',
       'analysis_neighborhood', 'supervisor_district',
       'supervisor_district_2012', 'latitude_x', 'longitude_x', 'point',
       ':@computed_region_26cr_cadq', ':@computed_region_qgnn_b9vv',
       ':@computed_region_jwn9_ihcz', ':@computed_region_h4ep_8xdi',
       ':@computed_region_nqbw_i6c3', ':@computed_region_n4xg_c4py',
       ':@computed_region_jg9y_a9du', 'ID', 'incident_datetime_y', 'day',
       'month', 'year', 'quarter', 'weekday', 'weekend', 'datetime_id',
       'incident_datetime', 'time', 'hour', 'minute', 'second', 'time_id',
       'latitude_y', 'longitude_y', 'location_id', 'incident_id_y',
       'incident_code_y', 'incident_category_y', 'incident_subcategory_y',
       'incident_description_y', 'Inci_id', 'resolution_y', 'resolution_id'],
      dtype='object')

In [31]:
complete_fact_table = fact_table[['incident_datetime_x', 'incident_date', 'incident_time',
       'incident_id_x', 'incident_number', 'report_type_code', 'incident_code_x', 'incident_category_x',
       'incident_subcategory_x', 'incident_description_x', 'resolution_x', 'police_district',
       'latitude_x', 'longitude_x', 'ID', 'day', 'month', 'year', 'quarter', 'weekday', 'weekend', 'datetime_id',
       'incident_datetime', 'time', 'hour', 'minute', 'second', 'time_id',
       'latitude_y', 'longitude_y', 'location_id', 'Inci_id', 'resolution_id']]

In [32]:
datetime_dim.to_csv("gs://project_major/Major_Project/PROCESSED/DATETIME_DIM.csv")

In [33]:
time_dim.to_csv("gs://project_major/Major_Project/PROCESSED/TIME_DIM.csv")

In [34]:
location_dim.to_csv("gs://project_major/Major_Project/PROCESSED/LOCATION_DIM.csv")

In [35]:
incident_dim.to_csv("gs://project_major/Major_Project/PROCESSED/INCIDENT_DIM.csv")

In [36]:
resolution_dim.to_csv("gs://project_major/Major_Project/PROCESSED/RESOLUTION_DIM.csv")

In [37]:
complete_fact_table.to_csv("gs://project_major/Major_Project/PROCESSED/FACT_TABLE.csv")

In [38]:
dataset_id = "Incident_Analysis"
project_id = "major-project-407515"
table_id = "datetime_dim"
datetime_dim.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 8774.69it/s]

In [39]:
table_id = "time_dim"
time_dim.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 3830.41it/s]

In [40]:
table_id = "location_dim"
location_dim.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 3063.77it/s]

In [41]:
table_id = "incident_dim"
incident_dim.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 9039.45it/s]

In [42]:
table_id = "resolution_dim"
resolution_dim.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 3350.08it/s]

In [43]:
table_id = "complete_fact_table"
complete_fact_table.to_gbq(destination_table=f'{project_id}.{dataset_id}.{table_id}', project_id=project_id, if_exists='replace')

100%|██████████| 1/1 [00:00<00:00, 3551.49it/s]